In [1]:
import pandas as pd
import numpy as np

from tqdm import tqdm
tqdm.pandas()

In [2]:
df = pd.read_csv('songdata.csv')
# df.drop(columns=['link'], inplace=True)

In [3]:
df = df.sample(10000, random_state=42).drop('link', axis=1).reset_index(drop=True)

In [4]:
df.head()

,artist,song,text
0,Wishbone Ash,Right Or Wrong,Like to have you 'round \nWith all the lies t...
1,Aerosmith,This Little Light Of Mine,"This Little Light of Mine (Light of Mine), \n..."
2,Fall Out Boy,"Dance, Dance",She says she's no good with words but I'm wors...
3,Janis Joplin,Easy Rider,"Hey mama, mama, come a look at sister, \nShe'..."
4,Moody Blues,Peak Hour,I see it all through my window it seems. \nNe...

In [5]:
df.shape

(10000, 3)

### Cleaning

In [6]:
df['text'][0]

"Like to have you 'round  \nWith all the lies that you make  \nThe things or darkness and you  \nSome people say, have just a taste  \nRight or wrong, you might get burned  \nWhat you gain is what you learn  \n  \nGot one too many women  \nDon't know quite which way to go  \nThey're all gettin' so expensive  \nWhen they walk by themselves  \nRight or wrong, don't regret  \nWhat you went for is what you get  \n  \nNo point in bitter tears  \nWhen someone else has cut you down  \n'Cause there's a time for leavin'  \nAnd there's a time for stickin' around, hey  \nRight or wrong, you've got to live  \nSo what you collect is what you give\n\n"

In [7]:
df['text'] = df['text'].str.lower().replace(r'[^\w\s]', '').replace(r'\n', ' ', regex=True)

In [8]:
df['text'][0]

"like to have you 'round   with all the lies that you make   the things or darkness and you   some people say, have just a taste   right or wrong, you might get burned   what you gain is what you learn      got one too many women   don't know quite which way to go   they're all gettin' so expensive   when they walk by themselves   right or wrong, don't regret   what you went for is what you get      no point in bitter tears   when someone else has cut you down   'cause there's a time for leavin'   and there's a time for stickin' around, hey   right or wrong, you've got to live   so what you collect is what you give  "

In [9]:
import nltk
from nltk.stem import PorterStemmer

In [10]:
ps = PorterStemmer()

In [11]:
def tokenization(text):
    tokens = nltk.word_tokenize(text)
    stemming = [ps.stem(token) for token in tokens]
    
    for token in tokens:
        stemming.append(ps.stem(token))
    return ' '.join(stemming)

In [12]:
df['text'] = df['text'].progress_apply(lambda x: tokenization(x))

100%|████████████████████████████████████████████████████████████████████████████| 10000/10000 [02:03<00:00, 80.84it/s]

In [13]:
df['text']

0       like to have you 'round with all the lie that ...
1       thi littl light of mine ( light of mine ) , i ...
2       she say she 's no good with word but i 'm wors...
3       hey mama , mama , come a look at sister , she ...
4       i see it all through my window it seem . never...
                              ...
9995    you know i 'm hotblood , babi ... get on up an...
9996    you 're the end of the rainbow , my pot of gol...
9997    artist : raw theme lyric song : across the nat...
9998    i wonder who 's sleep in your sheet tonight wh...
9999    when you 're drive down the highway at night a...
Name: text, Length: 10000, dtype: object

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [15]:
tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
matrix = tfidf.fit_transform(df['text'])

In [16]:
matrix.shape

(10000, 5000)

In [17]:
similarity = cosine_similarity(matrix)

In [18]:
similarity

array([[1.        , 0.        , 0.03701978, ..., 0.00997877, 0.05445446,
        0.04957703],
       [0.        , 1.        , 0.0215361 , ..., 0.01779531, 0.        ,
        0.03213981],
       [0.03701978, 0.0215361 , 1.        , ..., 0.0159194 , 0.04094327,
        0.01407595],
       ...,
       [0.00997877, 0.01779531, 0.0159194 , ..., 1.        , 0.        ,
        0.00202736],
       [0.05445446, 0.        , 0.04094327, ..., 0.        , 1.        ,
        0.01620602],
       [0.04957703, 0.03213981, 0.01407595, ..., 0.00202736, 0.01620602,
        1.        ]])

In [19]:
similarity.shape

(10000, 10000)

In [20]:
df['song'][0]

'Right Or Wrong'

In [21]:
df[df['song'] == 'Right Or Wrong']

,artist,song,text
0,Wishbone Ash,Right Or Wrong,like to have you 'round with all the lie that ...

In [22]:
# shows the similarity between the song to others
sorted(list(enumerate(similarity[0])), reverse=False, key = lambda x: x[1])

[(1, 0.0),
 (48, 0.0),
 (79, 0.0),
 (110, 0.0),
 (122, 0.0),
 (128, 0.0),
 (203, 0.0),
 (242, 0.0),
 (314, 0.0),
 (346, 0.0),
 (402, 0.0),
 (411, 0.0),
 (448, 0.0),
 (545, 0.0),
 (614, 0.0),
 (697, 0.0),
 (707, 0.0),
 (714, 0.0),
 (715, 0.0),
 (784, 0.0),
 (800, 0.0),
 (803, 0.0),
 (805, 0.0),
 (836, 0.0),
 (878, 0.0),
 (879, 0.0),
 (882, 0.0),
 (962, 0.0),
 (1016, 0.0),
 (1133, 0.0),
 (1225, 0.0),
 (1229, 0.0),
 (1286, 0.0),
 (1289, 0.0),
 (1303, 0.0),
 (1304, 0.0),
 (1319, 0.0),
 (1320, 0.0),
 (1363, 0.0),
 (1368, 0.0),
 (1434, 0.0),
 (1462, 0.0),
 (1484, 0.0),
 (1487, 0.0),
 (1492, 0.0),
 (1528, 0.0),
 (1545, 0.0),
 (1642, 0.0),
 (1775, 0.0),
 (1849, 0.0),
 (1881, 0.0),
 (1919, 0.0),
 (1965, 0.0),
 (2020, 0.0),
 (2053, 0.0),
 (2063, 0.0),
 (2083, 0.0),
 (2111, 0.0),
 (2147, 0.0),
 (2156, 0.0),
 (2157, 0.0),
 (2173, 0.0),
 (2175, 0.0),
 (2197, 0.0),
 (2266, 0.0),
 (2271, 0.0),
 (2287, 0.0),
 (2310, 0.0),
 (2363, 0.0),
 (2380, 0.0),
 (2444, 0.0),
 (2458, 0.0),
 (2490, 0.0),
 (2538, 0.0),
 (2552, 0.0),
 (2599, 0.0),
 (2647, 0.0),
 (2735, 0.0),
 (2743, 0.0),
 (2772, 0.0),
 (2800, 0.0),
 (2838, 0.0),
 (2887, 0.0),
 (3007, 0.0),
 (3051, 0.0),
 (3063, 0.0),
 (3090, 0.0),
 (3098, 0.0),
 (3102, 0.0),
 (3125, 0.0),
 (3173, 0.0),
 (3183, 0.0),
 (3187, 0.0),
 (3189, 0.0),
 (3190, 0.0),
 (3217, 0.0),
 (3221, 0.0),
 (3394, 0.0),
 (3503, 0.0),
 (3543, 0.0),
 (3686, 0.0),
 (3731, 0.0),
 (3766, 0.0),
 (3792, 0.0),
 (3856, 0.0),
 (3879, 0.0),
 (3887, 0.0),
 (3915, 0.0),
 (3941, 0.0),
 (4006, 0.0),
 (4118, 0.0),
 (4205, 0.0),
 (4236, 0.0),
 (4287, 0.0),
 (4349, 0.0),
 (4382, 0.0),
 (4418, 0.0),
 (4528, 0.0),
 (4530, 0.0),
 (4531, 0.0),
 (4535, 0.0),
 (4581, 0.0),
 (4584, 0.0),
 (4647, 0.0),
 (4740, 0.0),
 (4781, 0.0),
 (4812, 0.0),
 (4814, 0.0),
 (4860, 0.0),
 (4883, 0.0),
 (4893, 0.0),
 (4962, 0.0),
 (4977, 0.0),
 (5009, 0.0),
 (5056, 0.0),
 (5076, 0.0),
 (5081, 0.0),
 (5120, 0.0),
 (5385, 0.0),
 (5435, 0.0),
 (5588, 0.0),
 (5654, 0.0),
 (5744, 0.0),
 (5771, 0.0),
 (5833, 0.0),
 (5843, 0.0),
 (5900, 0.0),
 (5935, 0.0),
 (5949, 0.0),
 (6018, 0.0),
 (6025, 0.0),
 (6073, 0.0),
 (6155, 0.0),
 (6247, 0.0),
 (6364, 0.0),
 (6401, 0.0),
 (6403, 0.0),
 (6410, 0.0),
 (6420, 0.0),
 (6427, 0.0),
 (6430, 0.0),
 (6446, 0.0),
 (6453, 0.0),
 (6530, 0.0),
 (6564, 0.0),
 (6712, 0.0),
 (6744, 0.0),
 (6790, 0.0),
 (6818, 0.0),
 (6844, 0.0),
 (6867, 0.0),
 (6889, 0.0),
 (6945, 0.0),
 (6959, 0.0),
 (6995, 0.0),
 (7041, 0.0),
 (7124, 0.0),
 (7131, 0.0),
 (7172, 0.0),
 (7195, 0.0),
 (7227, 0.0),
 (7235, 0.0),
 (7271, 0.0),
 (7299, 0.0),
 (7382, 0.0),
 (7447, 0.0),
 (7479, 0.0),
 (7605, 0.0),
 (7606, 0.0),
 (7628, 0.0),
 (7632, 0.0),
 (7639, 0.0),
 (7662, 0.0),
 (7675, 0.0),
 (7686, 0.0),
 (7741, 0.0),
 (7757, 0.0),
 (7758, 0.0),
 (7760, 0.0),
 (7824, 0.0),
 (7870, 0.0),
 (7902, 0.0),
 (8133, 0.0),
 (8141, 0.0),
 (8264, 0.0),
 (8318, 0.0),
 (8388, 0.0),
 (8420, 0.0),
 (8454, 0.0),
 (8458, 0.0),
 (8502, 0.0),
 (8504, 0.0),
 (8638, 0.0),
 (8662, 0.0),
 (8668, 0.0),
 (8687, 0.0),
 (8697, 0.0),
 (8737, 0.0),
 (8757, 0.0),
 (8769, 0.0),
 (8824, 0.0),
 (8882, 0.0),
 (8922, 0.0),
 (8927, 0.0),
 (8962, 0.0),
 (9019, 0.0),
 (9031, 0.0),
 (9070, 0.0),
 (9088, 0.0),
 (9095, 0.0),
 (9139, 0.0),
 (9272, 0.0),
 (9300, 0.0),
 (9324, 0.0),
 (9385, 0.0),
 (9389, 0.0),
 (9546, 0.0),
 (9559, 0.0),
 (9581, 0.0),
 (9706, 0.0),
 (9712, 0.0),
 (9774, 0.0),
 (9780, 0.0),
 (9857, 0.0),
 (9877, 0.0),
 (9880, 0.0),
 (9917, 0.0),
 (9924, 0.0),
 (9954, 0.0),
 (9996, 0.0),
 (7520, 0.0004643568537208807),
 (6351, 0.00047796861304546644),
 (3844, 0.0004780832102318991),
 (387, 0.0006811887662785144),
 (4623, 0.0007075877809907548),
 (4638, 0.0007124868697307889),
 (9291, 0.0008054595903629961),
 (877, 0.0008466927821771379),
 (8132, 0.000923620310950339),
 (398, 0.0009242984104662678),
 (4896, 0.0009667599645336827),
 (170, 0.0010065197661163266),
 (5765, 0.0010206530242076798),
 (1246, 0.001053982662781604),
 (4111, 0.0010707411403880816),
 (8874, 0.0010833084972381077),
 (7822, 0.0011447083036537904),
 (8195, 0.0011604344276022532),
 (6997, 0.0011693912030451728),
 (9542, 0.0011696434373014131),
 (9691, 0.001169784409402204),
 (2959, 0.0012267340537450426),
 (3793, 0.0012298339988353368),
 (5674, 0.001236534136807531),
 (4612, 0.001253745757945474),
 (8857, 0.0012606793681608703),
 (5873, 0.001263843081987876),
 (3377, 0.0013262097194571942),
 (1331, 0.0013495030807466517),
 (496, 0.0013539709894062277),
 (3112, 0.0013823217889614686),
 (6893, 0.0013839317066539712),
 (1036, 0.0013843307476499923),
 (6477, 0.0013941257685765995),
 (6356, 0.0013949893403088632),
 (4703, 0.0013955838574033178),
 (6506, 0.001396147305333108),
 (9631, 0.001427920947249241),
 (3590, 0.001428055950798051),
 (7072, 0.0014585334599936477),
 (1963, 0.0014938369140444251),
 (3694, 0.0015212013952813053),
 (3457, 0.001530451083409824),
 (7496, 0.0015365497077726663),
 (7406, 0.0015422723224488238),
 (8062, 0.001542558570313939),
 (4390, 0.0015511354982470661),
 (1349, 0.001552811934755335),
 (5406, 0.0016276959381610774),
 (1739, 0.0016655567842511162),
 (5669, 0.0016833916588248497),
 (7455, 0.0017153959520734977),
 (8246, 0.00174284052748419),
 (8631, 0.0017669650809041227),
 (2206, 0.0017725186538297172),
 (5444, 0.0017899755571445302),
 (125, 0.0017959632965751132),
 (2104, 0.0018457664042029502),
 (37, 0.0018477066213758392),
 (9096, 0.0018948756839632758),
 (4271, 0.0019104499648013957),
 (3757, 0.0019250843627752004),
 (2935, 0.001927140076023373),
 (1182, 0.0019350798086491948),
 (4694, 0.001942817198037977),
 (7669, 0.0019578106835734022),
 (1996, 0.0019588247505051967),
 (5306, 0.001962306569710488),
 (6248, 0.001977106607221982),
 (3340, 0.0019771540796957717),
 (7459, 0.0019825212728686653),
 (7209, 0.0019837122698833265),
 (831, 0.0019856491503120422),
 (1248, 0.0019861585277710873),
 (7248, 0.0020045457845913077),
 (6242, 0.0020292667409475386),
 (6784, 0.0020498717038363702),
 (5661, 0.002074623670218879),
 (1496, 0.0020808425400466904),
 (251, 0.002085825724341382),
 (4224, 0.0020925623103934888),
 (9354, 0.0021046416519209304),
 (393, 0.0021214322108885223),
 (2685, 0.002156022133309428),
 (4440, 0.002158753367582344),
 (571, 0.002166057393779252),
 (3396, 0.0021689392611936933),
 (9555, 0.0021719195315836526),
 (1435, 0.0021780623690520855),
 (531, 0.0021867903812073227),
 (3444, 0.002189803607453901),
 (7682, 0.00219769185399891),
 (924, 0.0022006788389652776),
 (8765, 0.0022091254275510355),
 (5448, 0.0022143871792890094),
 (6662, 0.0022179419799865843),
 (8193, 0.002231521827039022),
 (9421, 0.002253263214108474),
 (1516, 0.0022616408645288063),
 (8624, 0.002262402200054068),
 (3296, 0.002266072749059675),
 (4203, 0.002270321513053383),
 (9165, 0.002288521715619307),
 (9621, 0.0023049636858893286),
 (7381, 0.0023178968990478764),
 (357, 0.0023202424759406546),
 (7388, 0.002329921643993054),
 (7189, 0.0023391117446283833),
 (9022, 0.0023571933210119163),
 (7361, 0.0023588102113720056),
 (6380, 0.0023640280456199364),
 (9657, 0.0024052807222159907),
 (6515, 0.002415687558694275),
 (7620, 0.0024306677666528567),
 (8834, 0.0024514286418971733),
 (439, 0.0024602103123196393),
 (2976, 0.002460330897679402),
 (1912, 0.0024642680943971567),
 (5563, 0.0024886932588953055),
 (8837, 0.0025092682486654635),
 (8784, 0.002512205180976608),
 (2131, 0.0025201749691763755),
 (7586, 0.002541371868865579),
 (8228, 0.0025604946592416465),
 (5106, 0.0025728712785312484),
 (6518, 0.0025830315527358414),
 (1222, 0.0025891465302545504),
 (7444, 0.0025899347412464855),
 (9784, 0.002605525224259421),
 (781, 0.0026314618598748023),
 (2356, 0.002650885932348127),
 (8354, 0.0026536708187944935),
 (1479, 0.0026547701956918988),
 (4057, 0.002657490249535184),
 (3456, 0.002670884104093667),
 (6074, 0.0026957113446765438),
 (7816, 0.00272311985022183),
 (4747, 0.00272785093053861),
 (4332, 0.0027359348041322983),
 (522, 0.002747467157124875),
 (3683, 0.0027626571009535888),
 (489, 0.002771128667028288),
 (5924, 0.0027950163576796134),
 (6437, 0.0028137040983247413),
 (3551, 0.0028196553409157257),
 (2217, 0.002828956453766414),
 (5286, 0.002837579791100253),
 (8189, 0.0028452022156039676),
 (9015, 0.002848270674759626),
 (3648, 0.0028547077869959608),
 (1345, 0.0029310111113994256),
 (6631, 0.0029324871191036385),
 (6773, 0.002940244076112383),
 (9145, 0.0029597866482468857),
 (1299, 0.0029642800542867796),
 (8080, 0.0029716887471984777),
 (5706, 0.0029904844714243044),
 (9487, 0.0029952308353675228),
 (2218, 0.003031823944149702),
 (1101, 0.0030334404775601786),
 (8008, 0.0030505124113145233),
 (2164, 0.0030516306038785453),
 (78, 0.0030567938017259356),
 (3194, 0.0030760774858645977),
 (9795, 0.003076418768887703),
 (447, 0.003091216754525788),
 (5853, 0.003101005935176215),
 (5664, 0.0031059011580365104),
 (704, 0.0031320359333842254),
 (718, 0.003143719328067411),
 (8218, 0.003145671455853703),
 (9879, 0.003156336288138663),
 (7472, 0.0031778294557463175),
 (7332, 0.0031871502420072664),
 (6608, 0.003199476726057349),
 (3689, 0.003203238710094475),
 (2842, 0.0032072114538278748),
 (7053, 0.003209290353560489),
 (2064, 0.0032100336297276157),
 (6654, 0.0032202600418241535),
 (8860, 0.0032394425805577247),
 (6165, 0.0032546964408942947),
 (3045, 0.003283255127028712),
 (6937, 0.0033273706782165277),
 (8565, 0.00335199477591731),
 (5386, 0.0033537627763033716),
 (6164, 0.0033682256066815764),
 (5986, 0.0033783306821546814),
 (5610, 0.003388739715958913),
 (3265, 0.0033984251231899522),
 (3656, 0.0034115091196277804),
 (8404, 0.0034179753187643467),
 (7684, 0.0034289654200179973),
 (148, 0.0034591919839977673),
 (995, 0.0034648633323302157),
 (1539, 0.0034667960382400538),
 (3885, 0.003467023267329904),
 (2914, 0.0034721274023670765),
 (2153, 0.003474230493684288),
 (7351, 0.0034817723351461163),
 (7540, 0.0035016510395542333),
 (222, 0.0035398074654918133),
 (7868, 0.003550819590765967),
 (8653, 0.00355758148251035),
 (5708, 0.0035637524536953347),
 (7279, 0.003567237307905379),
 (7250, 0.0035728468996359813),
 (1424, 0.003580792152083926),
 (2924, 0.0035845077242767664),
 (2160, 0.0035854056989196264),
 (3068, 0.0036145895485799324),
 (7857, 0.0036267100212906164),
 (8588, 0.0036625158983215446),
 (5626, 0.0036724740301928927),
 (316, 0.003688318709632975),
 (3255, 0.003692998231370332),
 (3033, 0.003729238644331137),
 (9688, 0.0037429828956225446),
 (1266, 0.0037513055632811283),
 (7118, 0.0037723961596121897),
 (6464, 0.00379137870766171),
 (5918, 0.0037920246932675317),
 (5555, 0.0038035454202125047),
 (4292, 0.0038058373233728414),
 (3651, 0.003806320714899939),
 (7997, 0.003815936614594744),
 (722, 0.00381727010865194),
 (2501, 0.0038474029311581005),
 (3376, 0.003859108971377662),
 (5307, 0.0038643061640967584),
 (7885, 0.003876612587499559),
 (2028, 0.0038805273569832255),
 (906, 0.003904297214514498),
 (576, 0.003906124310079944),
 (5051, 0.0039080101399357045),
 (9817, 0.0039112771655207415),
 (4300, 0.003934291047870221),
 (9060, 0.003937705429980329),
 (6930, 0.003939693507962236),
 (774, 0.003948555799631985),
 (5378, 0.003960049670107378),
 (3625, 0.003964027981935407),
 (1142, 0.003968519674581829),
 (6947, 0.003979372398015843),
 (7450, 0.004006670519874382),
 (1613, 0.0040249395496236556),
 (5305, 0.004027038042153397),
 (7674, 0.004028929299882891),
 (7198, 0.004053381483342422),
 (190, 0.004059498811338006),
 (8314, 0.004080568255670092),
 (2247, 0.004086711280618284),
 (5667, 0.004102031687104032),
 (8888, 0.0041048451968608785),
 (6540, 0.004136733459878106),
 (5556, 0.004151148806994217),
 (7373, 0.004152615225710634),
 (5049, 0.004163793710783273),
 (7556, 0.004166468226389456),
 (3840, 0.004169208529939093),
 (3945, 0.004184615438253685),
 (6641, 0.00418606114719912),
 (8471, 0.004246843903461541),
 (2330, 0.0042503935023136645),
 (3585, 0.004252539619627678),
 (3598, 0.004254229735897109),
 (5141, 0.00427743328432492),
 (4972, 0.004280581602558064),
 (6628, 0.004282286118377183),
 (6238, 0.0042918661628149595),
 (5012, 0.004315549960989784),
 (1717, 0.004334709726539328),
 (2802, 0.004337224911171228),
 (4180, 0.004337349438506599),
 (3667, 0.004349418468705041),
 (1282, 0.00435393352167866),
 (9048, 0.0043568863641335375),
 (3440, 0.004361739778837945),
 (934, 0.004363394419834646),
 (6223, 0.0043635797683985395),
 (5615, 0.004375662420773478),
 (4871, 0.0043833197371628985),
 (8171, 0.004385801784403577),
 (3110, 0.004425139430546172),
 (7994, 0.004426727065380476),
 (1329, 0.0044409703926392916),
 (202, 0.004445973778869161),
 (174, 0.00445772395453648),
 (6998, 0.004461734689421891),
 (7665, 0.0044649500254379275),
 (2937, 0.004468026719629937),
 (6635, 0.004502840173984843),
 (3083, 0.004504819889193301),
 (6701, 0.004505298663077858),
 (9150, 0.004527640100988051),
 (11, 0.004534069556992543),
 (644, 0.004547717817148464),
 (3353, 0.004547717817148464),
 (7353, 0.0045583361218426545),
 (2054, 0.004563090374001743),
 (1017, 0.004579227736255543),
 (2699, 0.004579333384514144),
 (3527, 0.004594453137066407),
 (4791, 0.004598301071577038),
 (8235, 0.004607174422109295),
 (5476, 0.004611159121597432),
 (4726, 0.004620368242580796),
 (2468, 0.004625164406864391),
 (6809, 0.004641286254122424),
 (3963, 0.004651177218893292),
 (8442, 0.004654408332448299),
 (2693, 0.004656587423233147),
 (3292, 0.004656593266451639),
 (2550, 0.004675441987806718),
 (43, 0.004686187596751274),
 (6024, 0.004697997010724811),
 (377, 0.004716021851102956),
 (7074, 0.0047278787046907585),
 (3367, 0.004740850199765627),
 (2484, 0.0047568922467281565),
 (8983, 0.004766213372118865),
 (9038, 0.0047776017865232695),
 (1504, 0.004787972776302597),
 (6583, 0.004789884676495463),
 (3964, 0.0047904725979231845),
 (8013, 0.004790581442505929),
 (177, 0.004795852667175883),
 (4776, 0.004796414641268627),
 (8263, 0.004805772702108592),
 (9166, 0.004810161238573319),
 (2908, 0.004825923403144658),
 (8379, 0.004839153073343201),
 (4030, 0.004848136545075646),
 (3563, 0.004853795629882556),
 (3520, 0.004857809074975652),
 (3728, 0.004867894444693291),
 (4821, 0.004874216414407925),
 (1476, 0.0048836911786912214),
 (5612, 0.004892803702908611),
 (8770, 0.004894151394283194),
 (2168, 0.0048976054818773394),
 (581, 0.004931801637010976),
 (8807, 0.004934460152212764),
 (996, 0.004949974343602986),
 (1038, 0.004963828129861521),
 (8839, 0.004967280744734673),
 (5327, 0.004972248774135026),
 (5240, 0.004980243111449676),
 (9236, 0.00499457793746692),
 (7671, 0.005003041695262411),
 (5251, 0.005050688898811276),
 (3123, 0.005050875931127796),
 (2011, 0.005071160647125372),
 (7592, 0.005076422567354124),
 (9377, 0.005090784022523932),
 (7383, 0.005104216040016532),
 (6345, 0.005119998677457505),
 (249, 0.005120011776659987),
 (8991, 0.005131862192613744),
 (6557, 0.005154499522208255),
 (3604, 0.005154936027675733),
 (5809, 0.005173706177494231),
 (3588, 0.0051747732689644225),
 (5748, 0.005181574189194576),
 (83, 0.005192453203013786),
 (1371, 0.005203586479010167),
 (9820, 0.0052069739563885475),
 (3832, 0.00520771205248642),
 (6977, 0.005209717835507326),
 (149, 0.005212023280731712),
 (1147, 0.0052142121044979825),
 (3994, 0.005224522862735339),
 (3030, 0.00522838449383908),
 (7192, 0.005233387286309842),
 (2913, 0.0052389009728424155),
 (7349, 0.00524639032571874),
 (5682, 0.005250727717441631),
 (6793, 0.005260964238211139),
 (4473, 0.005267589640795941),
 (5267, 0.005267724138025762),
 (5617, 0.005268632837146537),
 (8992, 0.0052715498893994095),
 (2162, 0.005278209406965039),
 (1339, 0.005295888867052786),
 (117, 0.005300656885615249),
 (7337, 0.0053101247245238205),
 (2616, 0.005331589863883522),
 (802, 0.005333336548698366),
 (2255, 0.005362017191438901),
 (4797, 0.005364724783860167),
 (7370, 0.005367840040824931),
 (9806, 0.0053784209590906455),
 (8190, 0.005380059710673291),
 (5157, 0.005389643089575299),
 (2288, 0.005405468145551589),
 (4888, 0.005408268203838401),
 (8629, 0.00541199812081403),
 (569, 0.005423378072483337),
 (827, 0.005424541987675193),
 (4417, 0.005426379720245859),
 (9247, 0.005454951047798992),
 (2862, 0.005465609984817506),
 (4886, 0.005472311244546548),
 (2050, 0.005485851082242888),
 (9387, 0.005488039973479896),
 (4404, 0.005514874362064626),
 (3681, 0.005519317730875677),
 (6405, 0.005521694290605254),
 (5323, 0.005530420908440832),
 (2920, 0.005540175296981282),
 (7630, 0.005547191545235736),
 (9067, 0.005555758833810545),
 (5358, 0.005561025624967716),
 (5535, 0.005564793563400828),
 (5805, 0.005569280612887098),
 (2034, 0.005570897440317916),
 (1556, 0.005571678972882703),
 (9457, 0.005577106346056806),
 (3789, 0.005587396104061242),
 (334, 0.005606543822661555),
 (5868, 0.005610878156144335),
 (1744, 0.005614658090316638),
 (9808, 0.0056248463124433535),
 (321, 0.005628857997305198),
 (1994, 0.005629268748307445),
 (2349, 0.005636490473078587),
 (687, 0.005641741160688597),
 (8933, 0.005644076379919415),
 (6047, 0.005645067037329558),
 (7723, 0.005649807931631709),
 (1406, 0.005665005413920298),
 (9437, 0.005681501205187966),
 (7644, 0.005695995611695202),
 (2030, 0.005710607496743129),
 (6315, 0.0057423235357477375),
 (4466, 0.005743113042535089),
 (2659, 0.005743810472141836),
 (7475, 0.00575426753995946),
 (9679, 0.00576250540900741),
 (2722, 0.00578304591545196),
 (9483, 0.005792460555337799),
 (3613, 0.005792911786248621),
 (7983, 0.005802032945608025),
 (5822, 0.005802442926305806),
 (7409, 0.005818408853473321),
 (3010, 0.005824379188132027),
 (1483, 0.005830096245122932),
 (2777, 0.005834302118767411),
 (2644, 0.005841119440153648),
 (541, 0.005863967952006909),
 (4983, 0.005869316271814154),
 (3432, 0.005871065954661745),
 (6431, 0.005874612570070582),
 (5082, 0.005885386044563757),
 (1822, 0.005898566653333431),
 (179, 0.00590704036566786),
 (2249, 0.005910257036014674),
 (8491, 0.005915329939533904),
 (6271, 0.005915618562023636),
 (3019, 0.0059549095439493435),
 (4818, 0.0059764070649650555),
 (4085, 0.005988947945267948),
 (1529, 0.005991584285915842),
 (467, 0.005992194338544285),
 (825, 0.006002228338886854),
 (2331, 0.00602091622314351),
 (1072, 0.006036468319361204),
 (807, 0.0060387058671895425),
 (9193, 0.00604163948800893),
 (3380, 0.00605052528643037),
 (5271, 0.006051443184514907),
 (8101, 0.006066570950907351),
 (8376, 0.006069499882325746),
 (6829, 0.0060902088225622195),
 (5368, 0.006091790411846035),
 (304, 0.006101076499313573),
 (2872, 0.006105425654108777),
 (7703, 0.006114558242834132),
 (1893, 0.006116106463909827),
 (6083, 0.006137574781336901),
 (1034, 0.006140763946717069),
 (5537, 0.006144954801589384),
 (6783, 0.00616756485842653),
 (2595, 0.006176935249691207),
 (6152, 0.006178833073416881),
 (8250, 0.006194928603090716),
 (8210, 0.006199044936119395),
 (1915, 0.006204096011395617),
 (3055, 0.0062077203050635),
 (4803, 0.00621507669291926),
 (8771, 0.006215440411532448),
 (2200, 0.006222030696075167),
 (5059, 0.006229051874419101),
 (5634, 0.00623169372505207),
 (9422, 0.006233664022016512),
 (8300, 0.006240781614420482),
 (1203, 0.0062529921548438805),
 (9994, 0.006254165369336906),
 (9352, 0.00626127032941981),
 (3150, 0.006270268706986532),
 (7550, 0.0062718184743564605),
 (3777, 0.006281075650967261),
 (2941, 0.006296339813395963),
 (4816, 0.006321174741030935),
 (7985, 0.006321221638197546),
 (5506, 0.006325228178443302),
 (808, 0.006328481967848034),
 (4543, 0.006337193760961453),
 (4913, 0.0063452526029421545),
 (9234, 0.006347017999734956),
 (3372, 0.006351707007043047),
 (9856, 0.006362640562669491),
 (4760, 0.006364818685958349),
 (3669, 0.006368403154164078),
 (2089, 0.006397948267858847),
 (7222, 0.006399425398677633),
 (2343, 0.006405796565638937),
 (3532, 0.006420768249579666),
 (4414, 0.006437137722208419),
 (2830, 0.006443729726643369),
 (5218, 0.0064575069926455335),
 (4109, 0.006468425906777753),
 (4141, 0.006478739885814849),
 (2580, 0.006483844770485721),
 (8296, 0.0065036986292562856),
 (620, 0.0065099850098486204),
 (3603, 0.0065341478381344175),
 (308, 0.006538709842700425),
 (3333, 0.006544660130022103),
 (8457, 0.006558133237484714),

In [26]:
def recommandation(song):
    if song not in df['song'].values:
        return f"Song '{song}' not found in the dataset."
    
    idx = df[df['song'] == song].index[0]
    
    distances = [(i, sim) for i, sim in enumerate(similarity[idx].flatten()) if i != idx]
    distances = sorted(distances, key=lambda x: x[1], reverse=True)
    
    songs = [df.iloc[i[0]]['song'] for i in distances[1:21]]
    
    return songs

In [27]:
recommandation('Right Or Wrong')

["I'm A Fool To Want You",
 'Where Did We Go Wrong',
 'Too Many Tears',
 'Without You',
 'Do The Right Thing',
 'Right Kind Of Wrong',
 'I Wonder Just Where I Went Wrong',
 'You Got No Right',
 'Wrong Way',
 "I've Been Wrong Before",
 "I'm Gonna Do It Right",
 'Any Way You Want It',
 "Nobody's Wrong",
 'Newborn',
 "I've Got A Right To Cry",
 'Doing All Right',
 'St. Ignatius',
 'One More Time',
 'No Authority',
 'Strong']

In [28]:
import pickle
pickle.dump(df, open('df.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))